var d = new Date();
console.log(d);
console.log(d.getTime());
console.log(d.getDate());
console.log(d.getDay());
console.log(d.getFullYear());
console.log(d.getMinutes());
console.log(d.getHours());
console.log(d.getMonth());
console.log(d.getTimezoneOffset());
// console.log(d.length);
console.log("over");